import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"CHATGPTAI_TG_BOT") 
SUDO=os.environ.get("SUDO","5910057231")
BOT_NAME = os.environ.get("BOT_NAME","CHATGPT BOT")
START_IMG = os.environ.get("START_IMG","https://te.legra.ph/file/9fa2101b77407dbec7d31.jpg")
STKR = os.environ.get("STKR","CAACAgEAAx0CRjAUHgABAsULZASkFZUsTQTw2k-FvC2SBJnd-vAAAokCAALW9iBFzemsQBDIqWkuBA")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","mr_sukkun")
OWNER_USERNAME = os.environ.get("OWNER_USERNAME","itz_legend_coder")
SUDO=os.environ.get("SUDO","5910057231")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","the_support_chat")
