import os
API_ID = int(os.environ.get("API_ID", "22825629"))
API_HASH = os.environ.get("API_HASH", "e8db542482a1638b4e5b03ed1ddae521") 
BOT_TOKEN = os.environ.get("BOT_TOKEN", "6536595310:AAEEBRUZoB5edG4xexWD8VZUCQVGeGFpC28") 
OPENAI_KEY = os.environ.get("OPENAI_KEY","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")
BOT_USERNAME = os.environ.get("BOT_USERNAME" "FRANKY_XNAKAMABOT") 
SUDO=os.environ.get("SUDO","6404342282")
BOT_NAME = os.environ.get("BOT_NAME", "FRANKY BOT NAKAMA PINTAR")
START_IMG = os.environ.get("START_IMG","https://te.legra.ph/file/9fa2101b77407dbec7d31.jpg")
STKR = os.environ.get("STKR","CAACAgEAAx0CRjAUHgABAsULZASkFZUsTQTw2k-FvC2SBJnd-vAAAokCAALW9iBFzemsQBDIqWkuBA")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL",None)
OWNER_USERNAME = os.environ.get("OWNER_USERNAME",None)
SUDO=os.environ.get("SUDO","6404342282")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","NAKAMA_ASL")
BARD_TOKEN=os.environ.get("BARD_TOKEN","")
